#
# Makefile for MacOS (Intel and/or Arm), Ubuntu Linux X86_64, RPi armv7l or aarch64, etc
#

UNAME_M := $(shell uname -m)
UNAME_S := $(shell uname -s)

# decide which CPU and which swich_to_stack code to use ...
ifeq ($(UNAME_M),arm64)
CPU=-DKERNEL64_ARCH_ARM64
K64_SWITCH_OBJ=	k64_switch_to_stack_arm64.o
endif
ifeq ($(UNAME_M),aarch64)
CPU=-DKERNEL64_ARCH_ARM64
K64_SWITCH_OBJ=	k64_switch_to_stack_arm64.o
endif
ifeq ($(UNAME_M),armv7l)
CPU=-DKERNEL64_ARCH_ARMV7L
# $(error Error: arm 32 bit not supported!)
CPU=-DKERNEL64_ARCH_ARM32
K64_SWITCH_OBJ=	k64_switch_to_stack_armv7l.o
endif
ifeq ($(UNAME_M),x86_64)
CPU=-DKERNEL64_ARCH_X86_64
K64_SWITCH_OBJ=	k64_switch_to_stack_x86_64.o
endif

# this is mainly because of different gcc versions...
ifeq ($(UNAME_S),Darwin)
STACK_SIZE=	-Wl,-stack_size,0x80000
endif
ifeq ($(OS_NAME), Linux)
STACK_SIZE=	-Wl,-z,stack_size=0x80000
endif

WARNINGS=	-Wno-comment \
		-Wno-deprecated-non-prototype \
		-Wno-extra-tokens \
		-Wno-implicit-function-declaration \
		-Wno-implicit-int \
		-Wno-incompatible-library-redeclaration \
		-Wno-incompatible-pointer-types-discards-qualifiers \
		-Wno-macro-redefined \
		-Wno-null-dereference
WARNINGS=

DEBUG=		-3 -O1 -Oi
DEBUG=		-g

CPPFLAGS=
INCLUDES=
CFLAGS=		$(INCLUDES) $(DEBUG) $(CPU) $(WARNINGS)
ASFLAGS=	$(DEBUG)
ARFLAGS=	-rv
LDFLAGS=	$(DEBUG) $(STACK_SIZE)

LIBKERNEL64=	kernel64.o $(K64_SWITCH_OBJ)

OBJS=		test_kernel.o $(LIBKERNEL64)

LIBS=		libkernel64.a

CMDS=		test_kernel

test_kernel:	test_kernel.o $(LIBS)
	$(CC) $(DEBUG) $(LDFLAGS) -o $@ $^

clean:
	rm -f $(OBJS)
	rm -f $(LIBS)
	rm -f $(CMDS)

libkernel64.a:	$(LIBKERNEL64)
	ar $(ARFLAGS) $@ $^

# Autogenerated - do not edit
test_kernel.o:	port.h kernel64.h
# LIBCLIENTS
kernel64.o:	port.h kernel64.h
