#
# Makefile for:
#	MacOS (Intel and/or Arm),
#	Ubuntu Linux x86_64 and/or i386,
#	RPi armv7l and/or aarch64, etc
#	Windows x86_64
#

UNAME_M := $(shell uname -m)

ifeq ($(OS),Windows_NT)
UNAME_S := Windows
else
UNAME_S := $(shell uname -s)
endif

# decide which CPU and which swich_to_stack code to use ...
ifeq ($(UNAME_M),arm64)
CPU=-DKERNEL64_ARCH_ARM64
K64_SWITCH_OBJ=k64_switch_to_stack_arm64.o
endif
ifeq ($(UNAME_M),aarch64)
CPU=-DKERNEL64_ARCH_ARM64
K64_SWITCH_OBJ=k64_switch_to_stack_arm64.o
endif
ifeq ($(UNAME_M),armv7l)
CPU=-DKERNEL64_ARCH_ARMV7L
CPU=-DKERNEL64_ARCH_ARM32
K64_SWITCH_OBJ=k64_switch_to_stack_armv7l.o
endif
ifeq ($(UNAME_M),x86_64)
ifeq ($(M32),-m32)
# cross compile from x86_64 machine to i386 target...
CPU=-DKERNEL64_ARCH_i386 -m32
K64_SWITCH_OBJ=k64_switch_to_stack_i386.o
else
CPU=-DKERNEL64_ARCH_X86_64
ifeq ($(UNAME_S),Windows)
K64_SWITCH_OBJ=k64_switch_to_stack_win64.o
else
K64_SWITCH_OBJ=k64_switch_to_stack_x86_64.o
endif
endif
endif

# filename extension for executable
ifeq ($(UNAME_S),Windows)
EXT=.exe
else
EXT=
endif

# save this for later ...
# $(error Error: cpu/arch not supported!)

# this is mainly because of different gcc versions...
ifeq ($(UNAME_S),Darwin)
STACK_SIZE=	-Wl,-stack_size,0x80000		# .5 MB
endif
ifeq ($(OS_NAME), Linux)
STACK_SIZE=	-Wl,-z,stack_size=0x80000	# .5 MB
endif
ifeq ($(UNAME_S),Windows)
STACK_SIZE=	-Wl,--stack,0x100000:0x80000	# 1 MB with .5 MB reserve (causes an error)
STACK_SIZE=	-Wl,--stack,0x100000		# 1 MB
endif

WARNINGS=	-Wno-comment \
		-Wno-deprecated-non-prototype \
		-Wno-extra-tokens \
		-Wno-implicit-function-declaration \
		-Wno-implicit-int \
		-Wno-incompatible-library-redeclaration \
		-Wno-incompatible-pointer-types-discards-qualifiers \
		-Wno-macro-redefined \
		-Wno-null-dereference
WARNINGS=

DEBUG=		-3 -O1 -Oi
DEBUG=		-g

CPPFLAGS=
INCLUDES=
CFLAGS=		$(DEBUG) $(CPU) $(INCLUDES) $(WARNINGS)
ASFLAGS=	$(DEBUG) $(CPU)
ARFLAGS=	-rv
LDFLAGS=	$(DEBUG) $(CPU) $(STACK_SIZE)

LIBKERNEL64=	kernel64.o kernel64util.o kernel64ps.o $(K64_SWITCH_OBJ)

OBJS=		test1_idle.o test2_kernel.o $(LIBKERNEL64)

LIBS=		libkernel64.a

CMDS=		test1_idle$(EXT) test2_kernel$(EXT)

ALL:		$(CMDS)

test1_idle$(EXT):	test1_idle.o $(LIBS)
	$(CC) $(DEBUG) $(LDFLAGS) -o $@ $^

test2_kernel$(EXT):	test2_kernel.o $(LIBS)
	$(CC) $(DEBUG) $(LDFLAGS) -o $@ $^

clean:
	rm -f $(OBJS)
	rm -f $(LIBS)
	rm -f $(CMDS)

libkernel64.a:	$(LIBKERNEL64)
	ar $(ARFLAGS) $@ $^

# Autogenerated - do not edit
# CMDS
test1_idle.o:	port.h kernel64.h
test2_kernel.o:	port.h kernel64.h
# LIBKERNEL64
kernel64.o:	port.h kernel64.h kernel64util.h
kernel64util.o:	port.h kernel64.h kernel64util.h
kernel64ps.o:	port.h kernel64.h
