name: C macOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check Environment Details
        run: |
          echo "Running on operating system:"
          sw_vers
          echo "Hardware architecture:"
          uname -m
          echo "System architecture:"
          uname -s
    - name: make
      run: make
