name: Kernel64 on macOS ARM C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # By default targets ARM based MacOS runner
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check Environment Details
      run: |
          echo "Running on operating system:"
          sw_vers
          echo "Hardware architecture:"
          uname -m
          echo "System architecture:"
          uname -s
          echo "Compiler architecture:"
          cc --version
    - name: make
      run: make test1_idle test2_kernel
    - name: test1_idle
      run: ./test1_idle
    - name: test2_kernel
      run: ./test2_kernel
