name: Kernel64 on Linux Ubuntu C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # Explicitly targets Intel x86_64 based Ubuntu runner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check Environment Details
      run: |
          echo "Running on operating system:"
          cat /etc/os-release
          echo "Hardware architecture:"
          uname -m
          echo "System architecture:"
          uname -s
          echo "Compiler architecture:"
          cc --version
    - name: make
      run: make test1_idle test2_kernel
    - name: test1_idle
      run: ./test1_idle
