name: Kernel64 on Linux Ubuntu C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # targets latest Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check Environment Details
      run: |
          echo "Hardware architecture:"
          uname -m
          echo "System architecture:"
          uname -s
    - name: make
      run: make test1_idle test2_kernel
