name: Kernel64 on Linux Ubuntu arm64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-on-ubuntu-arm64:
    # Explicitly target Ubuntu arm64
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
    - name: Check Environment Details
      run: |
          echo "Running on operating system:"
          cat /etc/os-release
          echo "Hardware architecture:"
          uname -m
          echo "System architecture:"
          uname -s
          echo "Compiler architecture:"
          cc --version
    - name: make
      run: make test1_idle test2_kernel
    - name: test1_idle
      run: ./test1_idle
    - name: test2_kernel
      run: ./test2_kernel
