name: Kernel64 on Windows Intel x86_64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-on-windows-x86_64:
    runs-on: windows-latest
    defaults:
      run:
        # Crucial: Forces GitHub Actions to run steps inside MSYS2 bash
        shell: msys2 {0}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up MSYS2 (Windows)
      if: ${{ runner.os == 'Windows' }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64		# vs older MINGW64
        update: true
        install: >-
          mingw-w64-ucrt-x86_64-gcc
          mingw-w64-ucrt-x86_64-gdb
          make
    - name: Check Environment Details (Windows)
      if: ${{ runner.os == 'Windows' }}
      run: |
          echo "Running on operating system:"
          echo $MSYSTEM
    - name: Check Environment Details
      run: |
          echo "Hardware architecture:"
          uname -m
          echo "System architecture:"
          uname -s
          echo "Compiler architecture:"
          gcc --version
    - name: make
      run: make CC=gcc test1_idle.exe test2_kernel.exe

#   - name: test1_idle.exe
#     continue-on-error: true
#     run: ./test1_idle.exe

#   - name: test2_kernel.exe
#     continue-on-error: true
#     run: ./test2_kernel.exe

    - name: gdb test1_idle.exe
      continue-on-error: true
      run: |
        gdb -batch \
            -ex "run" \
            -ex "thread apply all bt" \
            ./test1_idle.exe

    - name: gdb test2_kernel.exe
      continue-on-error: true
      run: |
        gdb -batch \
            -ex "run" \
            -ex "thread apply all bt" \
            ./test2_kernel.exe
